services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ../..:/workspace
      - python-packages:/usr/local/lib/python3.12/site-packages
    working_dir: /workspace
    
  r:
    image: r-base:4.4.0
    container_name: r-app
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    command: tail -f /dev/null

volumes:
  python-packages: